### ISSUE TITLE
Marche pô

### ISSUE THREAD

**Issue by jtremesay** [moleculext/taptempo#1]
j'ai beau presser des touches, il ne se passe rien. Même en appuyant sur [q].
> $ ./taptempo
Hit enter key for each beat (q to quit).
bbbbbbbbbbqqqqqqq^C
$

Testé sous Centos 6.

**Comment by jtremesay** [comment]
Neverwind, j'avais lu "press a key". Ça m'apprendra à tester avant le premier café.

**Comment by moleculext** [comment]
Pas de soucis, ça pourrait être une amélioration de pouvoir presser n'importe quelle touche.

Merci d'avoir testé :)
